### ISSUE TITLE
"Get Started" doesn't work as expected

### ISSUE THREAD

**Issue by lipingtababa** [selefra/registry#1]
# Problem
"Get Started" doesn't work as expected.

# To replicate

### Step 1:
My profile 'serverless' is working
```
machi@Mas-MacBook-Air selefra-demo % aws configure list --profile serverless  >/dev/null
machi@Mas-MacBook-Air selefra-demo % echo $?
0
machi@Mas-MacBook-Air selefra-demo % aws --profile serverless sts get-caller-identity  >/dev/null
machi@Mas-MacBook-Air selefra-demo % echo $?
0
```

### Step 2:
selefra.yaml is configured to use serverless profile
```yaml
selefra:
    name: selefra-demo
    cli_version: v0.0.6
    providers:
        - name: aws
          source: selefra/aws@v0.0.8
          version: v0.0.8
providers:
    - name: aws
      ##  Optional, Repeated. Add an accounts block for every account you want to assume-role into and fetch data from.
      accounts:
      #    #     Optional. User identification
        - account_name: serverless
      #    #    Optional. Named profile in config or credential file from where Selefra should grab credentials
          shared_config_profile: serverless
      #    #    Optional. Location of shared configuration files
      #    shared_config_files:
      #      - <FILE_PATH>
      #    #   Optional. Location of shared credentials files
      #    shared_credentials_files:
      #      - <FILE_PATH>
      #    #    Optional. Role ARN we want to assume when accessing this account
      #    role_arn: < YOUR_ROLE_ARN >
      #    #    Optional. Named role session to grab specific operation under the assumed role
      #    role_session_name: <SESSION_NAME>
      #    #    Optional. Any outside of the org account id that has additional control
      #    external_id: <ID>
      #    #    Optional. Designated region of servers
      #    default_region: <REGION_CODE>
      #    #    Optional. by default assumes all regions
          regions:
            - us-east-1
      #    The maximum number of times that a request will be retried for failures. Defaults to 10 retry attempts.
      max_attempts: 10
      #    The maximum back off delay between attempts. The backoff delays exponentially with a jitter based on the number of attempts. Defaults to 30 seconds.
      max_backoff: 30
```

### Step 3
selefra ignores the specified profile and returns 0.
```
machi@Mas-MacBook-Air selefra-demo % selefra apply
Initializing provider plugins...

Selefra has been successfully installed providers!

Checking Selefra provider updates......

	aws@v0.0.8 all ready updated!

Selefra has been finished update providers!

Client verification completed

Providers verification completed

Profile verification completed

Selefra exit
```

# Expected 
1. selefra works with the specified profile, or
2. selefra returns a detailed error msg
